### ISSUE TITLE
hyper parameter

### ISSUE THREAD

**Issue by DeepTiming** [hqucv/siamban#12]
How do you get the hyper parameter?
WINDOW_INFLUENCE: 0.4632532824922313  # VOT2018
PENALTY_K: 0.08513642556896711  # VOT2018
 LR: 0.44418184746462425  # VOT2018

thanks!

**Comment by zeduchen** [comment]
Please refer to [here](https://github.com/hqucv/siamban/blob/master/TRAIN.md#hyper-parameter-search).
