### ISSUE TITLE
Raw Result Testing On VOT2018

### ISSUE THREAD

**Issue by sunhao12121** [hqucv/siamban#13]
I download your Raw result (VOT2018)in google_drive and find the result in the first raw below 
-----------------------------------------------------------------
|  Tracker Name   | Accuracy | Robustness | Lost Number |  EAO  |
-----------------------------------------------------------------
|      model                |  0.590   |   0.178    |    38.0     | 0.447 |
|    SiamRPN++         |  0.601   |   0.234    |    50.0     | 0.415 |
|      ATOM                 |  0.590   |   0.203    |    43.4     | 0.400 |
|      LADCF                |  0.503   |   0.159    |    34.0     | 0.389 |
|       MFT                   |  0.505   |   0.140    |    30.0     | 0.385 |
| model_DaSiamRPN |  0.586   |   0.276    |    59.0     | 0.383 |
|     SiamRPN             |  0.586   |   0.276    |    59.0     | 0.383 |
|      UPDT                  |  0.536   |   0.184    |    39.2     | 0.378 |
|       RCO                   |  0.507   |   0.155    |    33.0     | 0.376 |
|       DRT                    |  0.519   |   0.201    |    43.0     | 0.356 |
|    DeepSTRCF           |  0.523   |   0.215    |    46.0     | 0.345 |
-----------------------------------------------------------------

From the result DaSiamRPN, my toolkit is ok. EAO is same as DaSiamRPN paper
if it is possible that I download the wrong data. From your paper EAO is *0.452*

By the way I run the model and the result is the same as the Raw result

I really hope for your help.

**Comment by zeduchen** [comment]
The small difference may be caused by different evaluation tools, you can try to use VOT2018 benchmark for evaluation.

**Comment by sunhao12121** [comment]
I see
