### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by sansanfree** [hqucv/siamban#14]
我发现你的代码是基于pysot的，你们都在epoches等于10的时候调整resnet50，我想问一下这样的调整会降低跟踪性能吗？我在训练siamrpn++的时候，发现了epoch>10后，测试效果变差（我怀疑是动了resnet50网络参数，引起了反作用），但是我发现你的学习率是从0.005到0.00005，siamrpn++是0.005到0.0005，也就是到了10 epoch时候，你的学习率会更低，此时会以更小的学习率调整resnet 50,所以你在epoch 10到20后，性能不会变差是吗

**Comment by Singapore-mor** [comment]
> 我发现你的代码是基于pysot的，你们都在epoches等于10的时候调整resnet50，我想问一下这样的调整会降低跟踪性能吗？我在训练siamrpn++的时候，发现了epoch>10后，测试效果变差（我怀疑是动了resnet50网络参数，引起了反作用），但是我发现你的学习率是从0.005到0.00005，siamrpn++是0.005到0.0005，也就是到了10 epoch时候，你的学习率会更低，此时会以更小的学习率调整resnet 50,所以你在epoch 10到20后，性能不会变差是吗

我也发现了这个问题

**Comment by Singapore-mor** [comment]
> > > 我发现你的代码是基于pysot的，你们都在epoches等于10的时候调整resnet50，我想问一下这样的调整会降低跟踪性能吗？我在训练siamrpn++的时候，发现了epoch>10后，测试效果变差（我怀疑是动了resnet50网络参数，引起了反作用），但是我发现你的学习率是从0.005到0.00005，siamrpn++是0.005到0.0005，也就是到了10 epoch时候，你的学习率会更低，此时会以更小的学习率调整resnet 50,所以你在epoch 10到20后，性能不会变差是吗
> > 
> > 
> > 我也发现了这个问题
> 
> 你测试效果差的多？还有如果你进行超参数调整，也就是hp_search.py函数，效果会接近论文的吗？
我还没用过hp_search.py这个函数进行超参数调整，你呢？

**Comment by ZikunZhou** [comment]
> > > 我发现你的代码是基于pysot的，你们都在epoches等于10的时候调整resnet50，我想问一下这样的调整会降低跟踪性能吗？我在训练siamrpn++的时候，发现了epoch>10后，测试效果变差（我怀疑是动了resnet50网络参数，引起了反作用），但是我发现你的学习率是从0.005到0.00005，siamrpn++是0.005到0.0005，也就是到了10 epoch时候，你的学习率会更低，此时会以更小的学习率调整resnet 50,所以你在epoch 10到20后，性能不会变差是吗
> > 
> > 
> > 我也发现了这个问题
> 
> 你测试效果差的多？还有如果你进行超参数调整，也就是hp_search.py函数，效果会接近论文的吗？
> 我还没用过hp_search.py这个函数进行超参数调整，你呢？

我测试10到20轮性能不会变差，但是不进行超参数调整，EAO远低于作者公布的结果，你尝试过进行超参数调整吗？

**Comment by zeduchen** [comment]
> 我发现你的代码是基于pysot的，你们都在epoches等于10的时候调整resnet50，我想问一下这样的调整会降低跟踪性能吗？我在训练siamrpn++的时候，发现了epoch>10后，测试效果变差（我怀疑是动了resnet50网络参数，引起了反作用），但是我发现你的学习率是从0.005到0.00005，siamrpn++是0.005到0.0005，也就是到了10 epoch时候，你的学习率会更低，此时会以更小的学习率调整resnet 50,所以你在epoch 10到20后，性能不会变差是吗

Yes.
