### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by kongbia** [hqucv/siamban#16]
Could you please provide the  download of the crop511 got_10k and lasot dataset

**Comment by wzwCVlearning** [comment]
Can anyone share the Baidu cloud link of youtube-bb?

**Comment by zeduchen** [comment]
> Could you please provide the download of the crop511 got_10k and lasot dataset

You can download them from the official website and use the tools we provide for processing. I will find a way to upload the cropped data to the network disk.

**Comment by zeduchen** [comment]
> Can anyone share the Baidu cloud link of youtube-bb?

You can check this [issue](https://github.com/hqucv/siamban/issues/11#issuecomment-629639059).
