### ISSUE TITLE
Some questions about the point_target.py

### ISSUE THREAD

**Issue by PHDJieFu** [hqucv/siamban#19]
About the function __call__() in the Class Point_target:
the code in function body of  "if neg："
neg = np.where(np.square(tcx - points[0]) / np.square(tw / 4) + np.square(tcy - points[1]) / np.square(th / 4) < 1)
Can anybody give some explain about this?

**Comment by zeduchen** [comment]
> About the function **call**() in the Class Point_target:
> the code in function body of "if neg："
> neg = np.where(np.square(tcx - points[0]) / np.square(tw / 4) + np.square(tcy - points[1]) / np.square(th / 4) < 1)
> Can anybody give some explain about this?

Please refer to this [issue](https://github.com/hqucv/siamban/issues/9).
