### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by zhu2014yi** [hqucv/siamban#2]
请问我跑这个train要跑多久，我是双1080ti 64G RAM

**Comment by zeduchen** [comment]
We have not tried using two 1080Ti GPUs, you can try it.

**Comment by zhu2014yi** [comment]
> We have not tried using two 1080Ti GPUs, you can try it.

那请问一下，你们是用多少张GPU，训练多少时间？

**Comment by zeduchen** [comment]
We used three GPUs for training and it took about 110 hours.
