### ISSUE TITLE
请问我运行Demo.py没有报错，就是图片显示不出来一闪而过，需要如何解决呢？

### ISSUE THREAD

**Issue by marico2020** [hqucv/siamban#20]
请问我运行Demo.py没有报错，就是图片显示不出来一闪而过，需要如何解决呢？

**Comment by zeduchen** [comment]
> 请问我运行Demo.py没有报错，就是图片显示不出来一闪而过，需要如何解决呢？

Can you provide more relevant information？

**Comment by Tangzhaotz** [comment]
try rename bag.avi as bag01.avi
