### ISSUE TITLE
can not download pretrained model

### ISSUE THREAD

**Issue by xiaodingkun-git** [hqucv/siamban#21]
i can not download the pretrained model,is it my problem or the author have not  published yet

**Comment by xiaodingkun-git** [comment]
i can not open the url provided by author ,is there a baiduyunpan link

**Comment by zeduchen** [comment]
Hi, the link has been added. The models can also be downloaded from [here](https://pan.baidu.com/s/1B4_E9O83dkH_AwEx8kiCzg), extraction code: `f5dz`.
