### ISSUE TITLE
results on VOT2018

### ISSUE THREAD

**Issue by Singapore-mor** [hqucv/siamban#22]
我下载了你传到model zoo的模型，但是我加载之后跑VOT2018，EAO只有0.358，想问下这是什么原因？

**Comment by xiaodingkun-git** [comment]
我怎么打不开modelzoo的链接，有其他的链接吗

**Comment by xiaodingkun-git** [comment]
> 我下载了你传到model zoo的模型，但是我加载之后跑VOT2018，EAO只有0.358，想问下这是什么原因？
我打不开modelzoo的链接 有其他的下载地址吗

**Comment by Singapore-mor** [comment]
> 我怎么打不开modelzoo的链接，有其他的链接吗

Git上给的是Google的网盘分享，你需要能翻墙才可以下载

**Comment by zeduchen** [comment]
> 我下载了你传到model zoo的模型，但是我加载之后跑VOT2018，EAO只有0.358，想问下这是什么原因？

Please check the evaluation environment.
