### ISSUE TITLE
model zoo

### ISSUE THREAD

**Issue by Tangzhaotz** [hqucv/siamban#24]
can't download the moodel

**Comment by zeduchen** [comment]
Hi, the models can also be downloaded from [here](https://pan.baidu.com/s/1B4_E9O83dkH_AwEx8kiCzg), extraction code: `f5dz`.

**Comment by Tangzhaotz** [comment]
> Hi, the models can also be downloaded from [here](https://pan.baidu.com/s/1B4_E9O83dkH_AwEx8kiCzg), extraction code: `f5dz`.

thank you
