### ISSUE TITLE
How to train model with other backbones ?

### ISSUE THREAD

**Issue by Yudachi-poi-poi** [hqucv/siamban#26]
Hi, I found mobilenet_v2.py, alexnet.py in folder model/backbone. Can someone tell me how to train model with other backbone and  how to config then config.yaml. Many thx！

**Comment by zeduchen** [comment]
Hello, you can refer to the configuration of (pysot)[https://github.com/STVIR/pysot].

**Comment by zeduchen** [comment]
Hello, you can refer to the configuration of [pysot](https://github.com/STVIR/pysot).
