### ISSUE TITLE
Some problems about the pre-processing for Lasot Dataset

### ISSUE THREAD

**Issue by PHDJieFu** [hqucv/siamban#27]
When I run the script gen_json.py in the .\LaSOT:
'No such file or directory: './LaSOT/testing_set.txt' ‘ will occur. Can you offer the link for this file (tesing_set.txt). Thanks a lot!

**Comment by zeduchen** [comment]
Hello, I uploaded [testing_set.txt](https://github.com/hqucv/siamban/blob/master/training_dataset/lasot/LaSOT/testing_set.txt).

**Comment by PHDJieFu** [comment]
> Hello, I uploaded [testing_set.txt](https://github.com/hqucv/siamban/blob/master/training_dataset/lasot/LaSOT/testing_set.txt).

Hello，Can you show the direction list of the GOT_10k dataset? Thanks a lot!

**Comment by zeduchen** [comment]
Just like  `pysot/training_dataset/lasot/LaSOT/airplane/airplane-1/`.
