### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Tangzhaotz** [hqucv/siamban#28]
Traceback (most recent call last):
  File "/home/tz/siamban/tools/test.py", line 21, in <module>
    from toolkit.utils.region import vot_overlap, vot_float2str
  File "/home/tz/siamban/toolkit/utils/__init__.py", line 1, in <module>
    from toolkit.utils import region
ImportError: cannot import name 'region' from 'toolkit.utils' (/home/tz/siamban/toolkit/utils/__init__.py)

what's the problem?how can i solve?

**Comment by XiaoBai-collab** [comment]
I think you can solve it according to this, 
Importerror: cannot import name region
Solution: Build region by python setup.py build_ext —-inplace as decribled in INSTALL.md.
(https://github.com/STVIR/pysot/blob/master/INSTALL.md)

**Comment by XiaoBai-collab** [comment]
@Tangzhaotz
I think you can solve it according to this,
Importerror: cannot import name region
Solution: Build region by python setup.py build_ext —-inplace as decribled in INSTALL.md.
(https://github.com/STVIR/pysot/blob/master/INSTALL.md)
