### ISSUE TITLE
Could you provide cropped youtube-bb dataset?

### ISSUE THREAD

**Issue by deneb2016** [hqucv/siamban#29]
I found baidu download link from https://github.com/hqucv/siamban/issues/11
But, I don't have baidu accout and I can't join baidu in South Korea.
Could you provide another link that I can access from Korea? (i.e. google drive, dropbox)

Thanks in advance

**Comment by zeduchen** [comment]
I did not save the cropped youtube-bb on google drive or dropbox, maybe you have to download and process it yourself.

**Comment by zeduchen** [comment]
We did not store the cropped youtube-bb on google drive or dropbox, you can try to download the original dataset and process it.
