### ISSUE TITLE
Different evaluation result

### ISSUE THREAD

**Issue by LouisShen233** [hqucv/siamban#3]
I used the raw result data and following the evaluation step to evaluate it on VOT2019, but I only got result: Accuracy=0.596, Robustness=0.396, EAO=0.322, which is a little worse than the result in the paper. Maybe I missed something?

**Comment by zeduchen** [comment]
It may be caused by different evaluation environment, you can try to use VOT2019 benchmark to evaluate.

**Comment by zeduchen** [comment]
It may be caused by different evaluation environment, you can try to use VOT2019 benchmark to evaluate.

**Comment by LouisShen233** [comment]
> It may be caused by different evaluation environment, you can try to use VOT2019 benchmark to evaluate.

OK. Are the results presented in paper evaluated by the VOT2019 benchmark tool?

**Comment by zeduchen** [comment]
Yes.
