### ISSUE TITLE
Result on VOT2018 

### ISSUE THREAD

**Issue by XJhaoren** [hqucv/siamban#32]
I train your SiamBAN base on all datasets('VID','YOUTUBEBB','COCO','DET','GOT10K','LASOT') and test on VOT2018. Before hyper-parameter search, the results are as following (Best EAO is 0.378):
![image](https://user-images.githubusercontent.com/30502323/93738360-29dd3900-fc18-11ea-9afe-1eac196aba90.png)

After  hyper-parameter search, the best EAO of  checkpoint_e13 is 0.400(which is much lower than 0.452). What is your EAO on VOT2018 before the hyper-parameter search? How much EAO can be improved by hyper-parametric search?

**Comment by zeduchen** [comment]
Are you using `tune.py` to search for hyper-parameters? And you should search on checkpoint_e20 and checkpoint_e19.

**Comment by XJhaoren** [comment]
Thank you very much! We used tune.py to search for hyper-parameters. We also search on checkpoint_e20 and checkpoint_e19, but the EAO is also about 0.4. We find that our yt-bb from pysot (https://github.com/STVIR/pysot/blob/master/TRAIN.md, YOUTUBEBB :New link for cropped data, BaiduYun, extract code: h964. NOTE: Data in old link is not correct. Please use cropped data in this new link) is already augmented.  Do you prepare yt-bb according to readme.md (https://github.com/hqucv/siamban/tree/master/training_dataset/yt_bb) in your project?

**Comment by zeduchen** [comment]
The score is indeed low before you search, you can check your environment. And how many times have you searched? The yt-bb we use is also from pysot.

**Comment by XJhaoren** [comment]
Thank you very much! I search about 300. How many times have you searched?

**Comment by zeduchen** [comment]
Generally, good results can be found by searching for more than 100 or more than 200. Also, Narrow the search range to find good results faster. When doing experiments, you can also use other test datasets, and the results will be more stable.

**Comment by XJhaoren** [comment]
Thanks very much!
