### ISSUE TITLE
iou loss and giou?

### ISSUE THREAD

**Issue by Tchuanm** [hqucv/siamban#33]
thanks for your great work .
1, I noticed that you used linear_iou loss but not giou in the code ,did u try the giou loss to train and is it worse than linear_iou reight?
2, I wanna  use giou loss or other iou loss to have a try ?  do you think it could be useful ?

**Comment by Tchuanm** [comment]
您好，关于您github提供的pth权重文件，
我通过在model zoo中下载并test，使用您程序中自带的eval.py计算出来的指标为 0.447/0.590/0.178
          主页标注的  VOT2018为(EAO/A./R.)   0.452/0.597/0.178,   其中的EAO和A两项指标均有一点差距
         同样的，我也评估了VOT2019，性能也存在一点差距EAO从0.327，我只得到了0.309。
         请问这是什么原因造成的呢？是必须使用VOT的toolkit，不能使用自带的eval.py评估吗？
          我开始以为是环境造成的，但新建了虚拟环境结果仍然这样，麻烦学长指点一下

**Comment by sysu-shey** [comment]
同问
