### ISSUE TITLE
point_target.py line35

### ISSUE THREAD

**Issue by ChenYang-1996** [hqucv/siamban#35]
if neg:
            neg = np.where(np.square(tcx - points[0]) / np.square(tw / 4) +
                           np.square(tcy - points[1]) / np.square(th / 4) < 1) #(pi,pj)falls within E2,why neg not pos?
            neg, neg_num = select(neg, cfg.TRAIN.NEG_NUM)
            cls[neg] = 0
            return cls, delta

the code comes from "point_target.py",it seems like don't run

**Comment by zeduchen** [comment]
It will run, you can look [here](https://github.com/hqucv/siamban/blob/714dffb6a98d5f18a60d1a7306de95fb80cfff47/siamban/datasets/dataset.py#L239).

**Comment by ChenYang-1996** [comment]
thank you so much! and I have a another question,in the "cd/experiments/config.yaml",how did you get these so accurate WINDOW_INFLUENCE,PENALTY_K and LR that  worked out 17  numbers behind decimal point?

**Comment by zeduchen** [comment]
Hello, you can get it with the [tune](https://github.com/hqucv/siamban/blob/master/tools/tune.py).

**Comment by ChenYang-1996** [comment]
thank you so much again! If possible,could you please tell me why the default batch_size=28,not 32,64,128......?

**Comment by zeduchen** [comment]
You're welcome. Because it is greater than 28, 11G video memory will be insufficient. You can configure it according to the model and GPU.
