### ISSUE TITLE
How to save the tracking results on a custom video ?

### ISSUE THREAD

**Issue by mylifeasazucchini** [hqucv/siamban#36]
Hi!

I'm extremely thankful to your work first of all! 
However, I had a query with regards to saving the bounding box estimates on a test video.

I have used the following python call

Python call:
python .\tools\demo.py --config .\experiments\siamban_r50_l234\config.yaml --snapshot .\experiments\siamban_r50_l234\model.pth --video .\demo\Copex_002_Block-02_Trial-02_0000047.avi --save

And I get the corresponding error:
Traceback (most recent call last):
  File ".\tools\demo.py", line 137, in <module>
    main()
  File ".\tools\demo.py", line 101, in main
    save_video_path = args.video_name.split(video_name)[0] + video_name + '_tracking.mp4'
ValueError: empty separator

But in any case this seems to be saving the whole visualization itself as a video itself and I'm not interested in that. Is there a way to be able to save just the bounding box estimates ?

Thanks in advance!

**Comment by zeduchen** [comment]
Hello, I don't know your needs well, you can modify the `demo.py` or `test.py` as needed.
