### ISSUE TITLE
请问你们在这六个数据集上训练一遍要多久

### ISSUE THREAD

**Issue by infinite013** [hqucv/siamban#40]
我在四张2080ti上要训练五天，这正常吗？

**Comment by zeduchen** [comment]
I feel a bit slow. You can check the `date_time`. If the `date_time` is longer, you can set a larger NUM_WORKERS, such as 8. And you can check [Issue 2](https://github.com/hqucv/siamban/issues/2).

**Comment by zeduchen** [comment]
I feel a bit slow. You can check the `date_time`. If the `date_time` is longer, you can set a larger `NUM_WORKERS`, such as `8`. And you can check [Issue 2](https://github.com/hqucv/siamban/issues/2).

**Comment by infinite013** [comment]
> I feel a bit slow. You can check the `date_time`. If the `date_time` is longer, you can set a larger `NUM_WORKERS`, such as `8`. And you can check [Issue 2](https://github.com/hqucv/siamban/issues/2).

Useful,thanks a lot.
