### ISSUE TITLE
My result is not as good as that in your paper

### ISSUE THREAD

**Issue by infinite013** [hqucv/siamban#43]
I trained my model on lasot,got-10k,coco,youtubebb and vid for 20 epochs.
And here is my result on VOT2018,EAO is 0.366
![QQ图片20201230110234](https://user-images.githubusercontent.com/37789662/103327326-0fc0bb80-4a8f-11eb-9010-a53e29da6b70.png)

looking forward to your reply ,thx

**Comment by zeduchen** [comment]
Please refer to the (Issue #42)[https://github.com/hqucv/siamban/issues/42].

**Comment by zeduchen** [comment]
Please refer to [Issue #42](https://github.com/hqucv/siamban/issues/42).
