### ISSUE TITLE
results on VOT2018 

### ISSUE THREAD

**Issue by zhu2014yi** [hqucv/siamban#5]
hi, I try to train the siamban, but i got the results more lower than yours, is there something should be pay attention to.
![image](https://user-images.githubusercontent.com/42707205/81075472-004b9b80-8f1d-11ea-953d-17b16fe583ac.png)

**Comment by zeduchen** [comment]
Please check the training and test environment. And you can try the hyper-parameter search tool to adjust the hyper-parameters.

**Comment by zeduchen** [comment]
> hi, I try to train the siamban, but i got the results more lower than yours, is there something should be pay attention to.
> ![image](https://user-images.githubusercontent.com/42707205/81075472-004b9b80-8f1d-11ea-953d-17b16fe583ac.png)

Please check the training and test environment. And you can try the hyper-parameter search tool to adjust the hyper-parameters.

**Comment by zeduchen** [comment]
Please check the training and test environment. And you can try the hyper-parameter search tool to adjust the hyper-parameters.

**Comment by zhu2014yi** [comment]
ok thanks
