### ISSUE TITLE
running the demo with google colab

### ISSUE THREAD

**Issue by magrenimish** [hqucv/siamban#52]
Hi there,
I'm trying to run the demo code with bag.avi video file on google colab but I'm facing the issue of "Cannot connect to server X:". I think its due to some of the opencv commands like _cv2.selectROI_. Have you successfully been able to run the demo on google colab?

**Comment by zeduchen** [comment]
You can try to comment out `cv2.imshow(video_name, frame)`.

**Comment by magrenimish** [comment]
I tried that but colab seems to have issues with other opencv commands as well.

**Comment by zeduchen** [comment]
I haven't run it in colab, you can check it.

**Comment by kravrolens** [comment]
I have the same issue, have you solved it?
