### ISSUE TITLE
Fig5 attr problems

### ISSUE THREAD

**Issue by zhu2014yi** [hqucv/siamban#53]
Hi！
请问如何计算你论文中的图5中的各个属性，我通过vot-toolkit工具包得到了如下的结果但是具体数值和你论文中对不上
![image](https://user-images.githubusercontent.com/42707205/113292506-30ffa500-9327-11eb-8863-0daa65ce6a55.png)
（还没使用VisualTracking-Toolkit工具包话那个属性图，因为缺少数据）

**Comment by zeduchen** [comment]
Hi, the score in Figure 5 is EAO.

**Comment by zhu2014yi** [comment]
> Hi, the score in Figure 5 is EAO.
就是各个属性的EAO是怎么计算得到的，我用siamban里面的eval只能得到总的一个EAO不能得到各个属性的EAO(illumination change, occlusion, size change, motion change, unassigned, camera motion）
![image](https://user-images.githubusercontent.com/42707205/113424218-57ded980-9402-11eb-8824-1ce66a8c1705.png)

**Comment by zeduchen** [comment]
The vot-toolkit tool calculates the EAO score of each attribute, but you need to save the data yourself.

**Comment by zhu2014yi** [comment]
> The vot-toolkit tool calculates the EAO score of each attribute, but you need to save the data yourself.

I see, thanks.
