### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by Singapore-mor** [hqucv/siamban#6]
I use parts of GOT10K dataset to train the model,when reached the 11th epoch，it raise the "CUDA out of memory"，I tried to decrease the batchsize ,but it did't work. Did you have this problem, or could you give me some advices? Thanks a lot

**Comment by zeduchen** [comment]
You can check whether the video memory is occupied before starting the training.

**Comment by Singapore-mor** [comment]
> You can check whether the video memory is occupied before starting the training.

How can i train on single gpu? I tried to change the CUDA_VISIBLE_DEVICES=0 and the node =1，I found the train result is worse, the bbox can't change its size, did I operate wrong?

**Comment by zeduchen** [comment]
CUDA_VISIBLE_DEVICES=0
python -m torch.distributed.launch \
    --nproc_per_node=1 \
    --master_port=2333 \
    ../../tools/train.py --cfg config.yaml

**Comment by nimishmagre** [comment]
> I use parts of GOT10K dataset to train the model,when reached the 11th epoch，it raise the "CUDA out of memory"，I tried to decrease the batchsize ,but it did't work. Did you have this problem, or could you give me some advices? Thanks a lot

Hey were you able to train on the single GPU?
if yes, how long did it take to complete training?
