### ISSUE TITLE
Code for plotting Fig 3,5,6,8

### ISSUE THREAD

**Issue by wangzheallen** [hqucv/siamban#7]
This is a nice work and figure looks nice!
Could you please share some draft code to plot 
fig 3,5,6,8?

Thank!

**Comment by zeduchen** [comment]
Figure 3 is drawn with PowerPoint, Figures 5 and 6 are drawn with [VisualTracking-Toolkit](https://github.com/foolwood/VisualTracking-Toolkit), and the drawing tool of Figure 8 is in our code.

**Comment by bluoluo** [comment]
> Figure 3 is drawn with PowerPoint, Figures 5 and 6 are drawn with [VisualTracking-Toolkit](https://github.com/foolwood/VisualTracking-Toolkit), and the drawing tool of Figure 8 is in our code.


Hi, your work is great! How is the value of `unassigned` in Figure 5 (`Comparison attributes`) calculated? My eval_tool is `pysot toolkit`, but the `unassigned` value cannot be calculated. I wonder if you know how to solve it? 
Thank!
