### ISSUE TITLE
关于训练 GOT10k数据集的问题

### ISSUE THREAD

**Issue by long-wa** [hqucv/siamban#74]
您好，如果用从pysot对GOT10k数据集生成的 train.json文件来训练，你们的代码 dataset.py中并不匹配这个json文件，这个是不是有点问题。如果想用GOT10k数据集进行训练的话是不是需要自己改写一下dataset中的相关代码以进行匹配

**Comment by bendta100** [comment]
我也有同样的问题，不知道楼主解决了没有，而且利用got_10k里的parse_got10k.py文件生成的json文件我的竟然有100多g，但还是无法匹配dataset.py里要求的格式问题

**Comment by wjh-scut** [comment]
> 我也有同样的问题，不知道楼主解决了没有，而且利用got_10k里的parse_got10k.py文件生成的json文件我的竟然有100多g，但还是无法匹配dataset.py里要求的格式问题

你好，我也遇到了同样的问题，请问您解决了吗？
