### ISSUE TITLE
Ques about point_target.py

### ISSUE THREAD

**Issue by Singapore-mor** [hqucv/siamban#9]
```
if neg: 
            neg = np.where(np.square(tcx - points[0]) / np.square(tw / 4) +
                           np.square(tcy - points[1]) / np.square(th / 4) < 1)
            neg, neg_num = select(neg, cfg.TRAIN.NEG_NUM)
            cls[neg] = 0 
```
I don't know the  `neg` means and the condition of np.where() doesn't means the pos? Looking forward your reply

**Comment by zeduchen** [comment]
Sample Negative pair see [DaSiamRPN](https://arxiv.org/pdf/1808.06048) for detail discussion.

**Comment by zeduchen** [comment]
For negative sample pairs, please refer to [DaSiamRPN](https://arxiv.org/pdf/1808.06048) for a detailed discussion.

**Comment by zeduchen** [comment]
For negative sample pairs, please refer to [DaSiamRPN](https://arxiv.org/pdf/1808.06048.pdf) for a detailed discussion.
